import type { RankingPlayer } from "@/types/contest";

/** Deterministic hero demo only — not live Week 1 ballots/consensus. */
export const HERO_DEMO_RB_RANKED: RankingPlayer[] = [
  {
    id: "demo-rb-1",
    name: "Bijan Robinson",
    team: "ATL",
    opponent: "vs MIN",
    position: "rb",
    gameDay: "Sun",
    gameTime: "1:00 PM",
    availability: "active",
  },
  {
    id: "demo-rb-2",
    name: "Jahmyr Gibbs",
    team: "DET",
    opponent: "@ GB",
    position: "rb",
    gameDay: "Sun",
    gameTime: "4:25 PM",
    availability: "active",
  },
  {
    id: "demo-rb-3",
    name: "Saquon Barkley",
    team: "PHI",
    opponent: "vs DAL",
    position: "rb",
    gameDay: "Sun",
    gameTime: "4:25 PM",
    availability: "active",
  },
  {
    id: "demo-rb-4",
    name: "Devon Achane",
    team: "MIA",
    opponent: "@ NE",
    position: "rb",
    gameDay: "Sun",
    gameTime: "1:00 PM",
    availability: "active",
  },
  {
    id: "demo-rb-5",
    name: "Jonathan Taylor",
    team: "IND",
    opponent: "vs HOU",
    position: "rb",
    gameDay: "Sun",
    gameTime: "1:00 PM",
    availability: "active",
  },
  {
    id: "demo-rb-6",
    name: "Kyren Williams",
    team: "LAR",
    opponent: "@ SEA",
    position: "rb",
    gameDay: "Sun",
    gameTime: "4:05 PM",
    availability: "active",
  },
  {
    id: "demo-rb-7",
    name: "Breece Hall",
    team: "NYJ",
    opponent: "vs BUF",
    position: "rb",
    gameDay: "Sun",
    gameTime: "1:00 PM",
    availability: "questionable",
  },
  {
    id: "demo-rb-8",
    name: "Josh Jacobs",
    team: "GB",
    opponent: "vs DET",
    position: "rb",
    gameDay: "Sun",
    gameTime: "4:25 PM",
    availability: "active",
  },
  {
    id: "demo-rb-9",
    name: "James Cook",
    team: "BUF",
    opponent: "@ NYJ",
    position: "rb",
    gameDay: "Sun",
    gameTime: "1:00 PM",
    availability: "active",
  },
  {
    id: "demo-rb-10",
    name: "Chase Brown",
    team: "CIN",
    opponent: "@ CLE",
    position: "rb",
    gameDay: "Sun",
    gameTime: "1:00 PM",
    availability: "active",
  },
];

export const HERO_DEMO_RB_POOL: RankingPlayer[] = [
  ...HERO_DEMO_RB_RANKED,
  {
    id: "demo-rb-11",
    name: "Alvin Kamara",
    team: "NO",
    opponent: "vs ARI",
    position: "rb",
    gameDay: "Sun",
    gameTime: "1:00 PM",
    availability: "active",
  },
  {
    id: "demo-rb-12",
    name: "Tony Pollard",
    team: "TEN",
    opponent: "@ DEN",
    position: "rb",
    gameDay: "Sun",
    gameTime: "4:05 PM",
    availability: "active",
  },
  {
    id: "demo-rb-13",
    name: "David Montgomery",
    team: "DET",
    opponent: "@ GB",
    position: "rb",
    gameDay: "Sun",
    gameTime: "4:25 PM",
    availability: "active",
  },
];

export const HERO_DEMO_CONSENSUS_ROWS = [
  {
    consensusRank: 1,
    name: "Bijan Robinson",
    selectionRate: 0.942,
    averageSelectedRank: 1.6,
    team: "ATL",
    opponent: "vs MIN",
    ballots: 128,
  },
  {
    consensusRank: 2,
    name: "Jahmyr Gibbs",
    selectionRate: 0.911,
    averageSelectedRank: 2.3,
    team: "DET",
    opponent: "@ GB",
    ballots: 128,
  },
  {
    consensusRank: 3,
    name: "Saquon Barkley",
    selectionRate: 0.875,
    averageSelectedRank: 2.9,
    team: "PHI",
    opponent: "vs DAL",
    ballots: 128,
  },
  {
    consensusRank: 4,
    name: "Devon Achane",
    selectionRate: 0.828,
    averageSelectedRank: 4.4,
    team: "MIA",
    opponent: "@ NE",
    ballots: 128,
  },
  {
    consensusRank: 5,
    name: "Jonathan Taylor",
    selectionRate: 0.781,
    averageSelectedRank: 5.1,
    team: "IND",
    opponent: "vs HOU",
    ballots: 128,
  },
  {
    consensusRank: 6,
    name: "Kyren Williams",
    selectionRate: 0.734,
    averageSelectedRank: 5.8,
    team: "LAR",
    opponent: "@ SEA",
    ballots: 128,
  },
  {
    consensusRank: 7,
    name: "Breece Hall",
    selectionRate: 0.688,
    averageSelectedRank: 6.7,
    team: "NYJ",
    opponent: "vs BUF",
    ballots: 128,
  },
  {
    consensusRank: 8,
    name: "Josh Jacobs",
    selectionRate: 0.641,
    averageSelectedRank: 7.2,
    team: "GB",
    opponent: "vs DET",
    ballots: 128,
  },
] as const;

export const HERO_DEMO_FILTERS = [
  "All",
  "Humans",
  "Experts",
  "Creators",
  "AI",
] as const;
