ALTER TABLE "Season" ADD COLUMN "fantasyScoringVersion" TEXT NOT NULL DEFAULT 'FANTASYTRACK_NFL_FULL_PPR_V1';

ALTER TABLE "Week" ALTER COLUMN "fantasyScoringVersion" SET DEFAULT 'FANTASYTRACK_NFL_FULL_PPR_V1';

UPDATE "Season" SET "fantasyScoringVersion" = 'FANTASYTRACK_NFL_FULL_PPR_V1' WHERE "fantasyScoringVersion" IS NULL;
